// Project
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const ARCHIVE_PROJECT = 'ARCHIVE_PROJECT';
export const EXPORT_PROJECT = 'EXPORT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_LOADING = 'PROJECT_LOADING';

// Error codes
export const GET_ERROR_CODES = 'GET_ERROR_CODES';
export const GET_ERROR_CODE = 'GET_ERROR_CODE';
export const CREATE_ERROR_CODE = 'CREATE_ERROR_CODE';
export const UPDATE_ERROR_CODE = 'UPDATE_ERROR_CODE';
export const DELETE_ERROR_CODE  = 'DELETE_ERROR_CODE';